import type { Metadata, Viewport } from "next";
import { Suspense } from "react";
import { headers } from "next/headers";
import { GeistSans } from "geist/font/sans";
import { GeistMono } from "geist/font/mono";

import { UserProvider } from "@/components/UserProvider";
import { getCurrentUser } from "@/lib/authcachetest";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export async function generateViewport(): Promise<Viewport> {
  await headers();

  return {
    width: "device-width",
    initialScale: 1,
  };
}

function RootBodyFallback() {
  return (
    <body className="flex h-full flex-col bg-zinc-50 text-zinc-950 dark:bg-zinc-950 dark:text-zinc-50" />
  );
}

async function RootBody({
  children,
}: {
  children: React.ReactNode;
}) {
  const user = await getCurrentUser();

  return (
    <body className="flex h-full flex-col bg-zinc-50 text-zinc-950 dark:bg-zinc-950 dark:text-zinc-50">
      <UserProvider user={user}>{children}</UserProvider>
    </body>
  );
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${GeistSans.variable} ${GeistMono.variable} h-full antialiased`}
    >
      <Suspense fallback={<RootBodyFallback />}>
        <RootBody>{children}</RootBody>
      </Suspense>
    </html>
  );
}
