import type { Metadata, Viewport } from "next";
import { Suspense } from "react";
import { GeistSans } from "geist/font/sans";
import { GeistMono } from "geist/font/mono";
import { headers } from "next/headers";

import { PerfBenchmarkWebVitals } from "@/components/PerfBenchmarkWebVitals";
import { SideNav } from "@/components/SideNav";
import { Toolbar } from "@/components/Toolbar";
import "../globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export async function generateViewport(): Promise<Viewport> {
  await headers();

  return {
    width: "device-width",
    initialScale: 1,
  };
}

export default function BlockingShellLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Suspense fallback={null}>
      <html
        lang="en"
        className={`${GeistSans.variable} ${GeistMono.variable} h-full antialiased`}
      >
        <body className="flex h-full flex-col bg-zinc-50 text-zinc-950 dark:bg-zinc-950 dark:text-zinc-50">
          <PerfBenchmarkWebVitals />
          <Toolbar />
          <div className="flex min-h-0 flex-1 flex-col md:flex-row">
            <SideNav />
            <div className="flex min-h-0 min-w-0 flex-1 flex-col">
              {children}
            </div>
          </div>
        </body>
      </html>
    </Suspense>
  );
}
